Grid layout Card
wolox-training/aor-react pull request #10
Opened 2018-10-08 20:04 UTC by Anisospina

## Summary
Add CSS grid layout
New design

## Trello Card:
https://trello.com/c/kLq95Kp0/12-redise%C3%B1o-de-la-p%C3%A1gina

2018-10-19 19:22 UTC, jmtov requested changes
Nice job! There are some things that need to be adjusted. Please check out my comments! 😺

2018-10-19 19:22 UTC, jmtov commented on Maquetado/scss/tech.scss
> +  grid-template-columns: 34% 33% 33%;
You can use the `repeat()` function here.

2018-10-19 19:22 UTC, jmtov commented on Maquetado/scss/tech.scss
> +  grid-template-rows: 38% 38% auto;
Do you really need this property here?

2018-10-19 19:22 UTC, jmtov commented on Maquetado/scss/tech.scss
> +  grid-template-columns: 34% 33% 33%;
Also, take a look at the `fr` unit: https://alligator.io/css/css-grid-layout-fr-unit/

2018-10-19 19:22 UTC, jmtov commented on Maquetado/scss/tech.scss
> +  width: 54%;
I'd recommend to set a `max-width` and leave the width to a 100%. Remember to test your layouts in different screen sizes!

2018-10-19 19:22 UTC, jmtov commented on Maquetado/scss/tech.scss
> +  &:nth-child(2) {
You don't need to define the position of every child within a grid layout. Well, at least not to achieve what the card defines.

2018-10-19 19:22 UTC, jmtov commented on Maquetado/scss/titles.scss
> +  width: 70%;
Do you really need to set the width on this element?

2018-10-19 21:00 UTC, jmtov requested changes

2018-10-19 21:00 UTC, jmtov commented on Maquetado/scss/tech.scss
> +    grid-row-start: 1;
I forgot to tell you, but you can use the `grid-row` shorthand here. 😅

2018-10-19 21:02 UTC, SKOLZ requested changes

2018-10-19 21:02 UTC, SKOLZ commented on Maquetado/index.html
> +
delete the spaces here

2018-10-19 21:02 UTC, SKOLZ commented on Maquetado/scss/navbar.scss
> +
delete the spaces

2018-10-19 21:19 UTC, SKOLZ requested changes

2018-10-19 21:19 UTC, SKOLZ commented on Maquetado/scss/tech.scss
> +    padding-top: 13em;
although this is not wrong, please use pixels to keep a fixed padding

2018-10-20 20:13 UTC, jmtov approved these changes

2018-10-21 03:10 UTC, SKOLZ approved these changes

2018-10-23 13:46 UTC, merged